apiVersion: v2
description: Benji Backup for Kubernetes
name: benji
version: 2.0.0
maintainers:
  - name: Elemental
    email: lf@elemental.net
dependencies:
  - name: postgresql
    version: ^12.2.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: prometheus-pushgateway
    alias: pushgateway
    version: ^2.1.3
    repository: https://prometheus-community.github.io/helm-charts
    condition: pushgateway.enabled
